// Code generated by psgo. DO NOT EDIT.

package Control_Category

import . "github.com/purescript-native/go-runtime"

import (
	"project.localhost/purescript-native/output/Control.Semigroupoid"
)

type _ = Any

func ꞋCategory_ṩDict() Any {
    return func(x Any) Any {
        return x
    }
}
func Ꞌidentity() Any {
    return func(dict Any) Any {
        return dict.(Dict)["identity"]
    }
}

var ᛌcategoryFn_once Once
var ᛧcategoryFn Any

func ꞋcategoryFn() Any {
    ᛌcategoryFn_once.Do(func() {
        ᛧcategoryFn = Dict{"identity": func(x Any) Any {
            return x
        }, "Semigroupoid0": func(_ Any) Any {
            return Control_Semigroupoid.ꞋsemigroupoidFn()
        },}
    })
return ᛧcategoryFn
}





