// Code generated by psgo. DO NOT EDIT.

package Effect_Uncurried

import . "github.com/purescript-native/go-runtime"

import (
	"project.localhost/purescript-native/output/Data.Semigroup"
	"project.localhost/purescript-native/output/Effect"
	"project.localhost/purescript-native/output/Data.Monoid"
)

type _ = Any

func ꞋsemigroupEffectFn9() Any {
    return func(dictSemigroup Any) Any {
        var append Any = Apply(Data_Semigroup.Ꞌappend(), Apply(Effect.ꞋsemigroupEffect(), dictSemigroup))
        return Dict{"append": func(f1 Any) Any {
                return func(f2 Any) Any {
                    return Apply(ꞋmkEffectFn9(), func(a Any) Any {
                        return func(b Any) Any {
                            return func(c Any) Any {
                                return func(d Any) Any {
                                    return func(e Any) Any {
                                        return func(f Any) Any {
                                            return func(g Any) Any {
                                                return func(h Any) Any {
                                                    return func(i Any) Any {
                                                        return Apply(append, Apply(ꞋrunEffectFn9(), f1, a, b, c, d, e, f, g, h, i), Apply(ꞋrunEffectFn9(), f2, a, b, c, d, e, f, g, h, i))
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    })
                }
            },}
    }
}
func ꞋsemigroupEffectFn8() Any {
    return func(dictSemigroup Any) Any {
        var append Any = Apply(Data_Semigroup.Ꞌappend(), Apply(Effect.ꞋsemigroupEffect(), dictSemigroup))
        return Dict{"append": func(f1 Any) Any {
                return func(f2 Any) Any {
                    return Apply(ꞋmkEffectFn8(), func(a Any) Any {
                        return func(b Any) Any {
                            return func(c Any) Any {
                                return func(d Any) Any {
                                    return func(e Any) Any {
                                        return func(f Any) Any {
                                            return func(g Any) Any {
                                                return func(h Any) Any {
                                                    return Apply(append, Apply(ꞋrunEffectFn8(), f1, a, b, c, d, e, f, g, h), Apply(ꞋrunEffectFn8(), f2, a, b, c, d, e, f, g, h))
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    })
                }
            },}
    }
}
func ꞋsemigroupEffectFn7() Any {
    return func(dictSemigroup Any) Any {
        var append Any = Apply(Data_Semigroup.Ꞌappend(), Apply(Effect.ꞋsemigroupEffect(), dictSemigroup))
        return Dict{"append": func(f1 Any) Any {
                return func(f2 Any) Any {
                    return Apply(ꞋmkEffectFn7(), func(a Any) Any {
                        return func(b Any) Any {
                            return func(c Any) Any {
                                return func(d Any) Any {
                                    return func(e Any) Any {
                                        return func(f Any) Any {
                                            return func(g Any) Any {
                                                return Apply(append, Apply(ꞋrunEffectFn7(), f1, a, b, c, d, e, f, g), Apply(ꞋrunEffectFn7(), f2, a, b, c, d, e, f, g))
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    })
                }
            },}
    }
}
func ꞋsemigroupEffectFn6() Any {
    return func(dictSemigroup Any) Any {
        var append Any = Apply(Data_Semigroup.Ꞌappend(), Apply(Effect.ꞋsemigroupEffect(), dictSemigroup))
        return Dict{"append": func(f1 Any) Any {
                return func(f2 Any) Any {
                    return Apply(ꞋmkEffectFn6(), func(a Any) Any {
                        return func(b Any) Any {
                            return func(c Any) Any {
                                return func(d Any) Any {
                                    return func(e Any) Any {
                                        return func(f Any) Any {
                                            return Apply(append, Apply(ꞋrunEffectFn6(), f1, a, b, c, d, e, f), Apply(ꞋrunEffectFn6(), f2, a, b, c, d, e, f))
                                        }
                                    }
                                }
                            }
                        }
                    })
                }
            },}
    }
}
func ꞋsemigroupEffectFn5() Any {
    return func(dictSemigroup Any) Any {
        var append Any = Apply(Data_Semigroup.Ꞌappend(), Apply(Effect.ꞋsemigroupEffect(), dictSemigroup))
        return Dict{"append": func(f1 Any) Any {
                return func(f2 Any) Any {
                    return Apply(ꞋmkEffectFn5(), func(a Any) Any {
                        return func(b Any) Any {
                            return func(c Any) Any {
                                return func(d Any) Any {
                                    return func(e Any) Any {
                                        return Apply(append, Apply(ꞋrunEffectFn5(), f1, a, b, c, d, e), Apply(ꞋrunEffectFn5(), f2, a, b, c, d, e))
                                    }
                                }
                            }
                        }
                    })
                }
            },}
    }
}
func ꞋsemigroupEffectFn4() Any {
    return func(dictSemigroup Any) Any {
        var append Any = Apply(Data_Semigroup.Ꞌappend(), Apply(Effect.ꞋsemigroupEffect(), dictSemigroup))
        return Dict{"append": func(f1 Any) Any {
                return func(f2 Any) Any {
                    return Apply(ꞋmkEffectFn4(), func(a Any) Any {
                        return func(b Any) Any {
                            return func(c Any) Any {
                                return func(d Any) Any {
                                    return Apply(append, Apply(ꞋrunEffectFn4(), f1, a, b, c, d), Apply(ꞋrunEffectFn4(), f2, a, b, c, d))
                                }
                            }
                        }
                    })
                }
            },}
    }
}
func ꞋsemigroupEffectFn3() Any {
    return func(dictSemigroup Any) Any {
        var append Any = Apply(Data_Semigroup.Ꞌappend(), Apply(Effect.ꞋsemigroupEffect(), dictSemigroup))
        return Dict{"append": func(f1 Any) Any {
                return func(f2 Any) Any {
                    return Apply(ꞋmkEffectFn3(), func(a Any) Any {
                        return func(b Any) Any {
                            return func(c Any) Any {
                                return Apply(append, Apply(ꞋrunEffectFn3(), f1, a, b, c), Apply(ꞋrunEffectFn3(), f2, a, b, c))
                            }
                        }
                    })
                }
            },}
    }
}
func ꞋsemigroupEffectFn2() Any {
    return func(dictSemigroup Any) Any {
        var append Any = Apply(Data_Semigroup.Ꞌappend(), Apply(Effect.ꞋsemigroupEffect(), dictSemigroup))
        return Dict{"append": func(f1 Any) Any {
                return func(f2 Any) Any {
                    return Apply(ꞋmkEffectFn2(), func(a Any) Any {
                        return func(b Any) Any {
                            return Apply(append, Apply(ꞋrunEffectFn2(), f1, a, b), Apply(ꞋrunEffectFn2(), f2, a, b))
                        }
                    })
                }
            },}
    }
}
func ꞋsemigroupEffectFn10() Any {
    return func(dictSemigroup Any) Any {
        var append Any = Apply(Data_Semigroup.Ꞌappend(), Apply(Effect.ꞋsemigroupEffect(), dictSemigroup))
        return Dict{"append": func(f1 Any) Any {
                return func(f2 Any) Any {
                    return Apply(ꞋmkEffectFn10(), func(a Any) Any {
                        return func(b Any) Any {
                            return func(c Any) Any {
                                return func(d Any) Any {
                                    return func(e Any) Any {
                                        return func(f Any) Any {
                                            return func(g Any) Any {
                                                return func(h Any) Any {
                                                    return func(i Any) Any {
                                                        return func(j Any) Any {
                                                            return Apply(append, Apply(ꞋrunEffectFn10(), f1, a, b, c, d, e, f, g, h, i, j), Apply(ꞋrunEffectFn10(), f2, a, b, c, d, e, f, g, h, i, j))
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    })
                }
            },}
    }
}
func ꞋsemigroupEffectFn1() Any {
    return func(dictSemigroup Any) Any {
        var append Any = Apply(Data_Semigroup.Ꞌappend(), Apply(Effect.ꞋsemigroupEffect(), dictSemigroup))
        return Dict{"append": func(f1 Any) Any {
                return func(f2 Any) Any {
                    return Apply(ꞋmkEffectFn1(), func(a Any) Any {
                        return Apply(append, Apply(ꞋrunEffectFn1(), f1, a), Apply(ꞋrunEffectFn1(), f2, a))
                    })
                }
            },}
    }
}
func ꞋmonoidEffectFn9() Any {
    return func(dictMonoid Any) Any {
        var mempty Any = Apply(Data_Monoid.Ꞌmempty(), Apply(Effect.ꞋmonoidEffect(), dictMonoid))
        var semigroupEffectFn91 Any = Apply(ꞋsemigroupEffectFn9(), Apply(dictMonoid.(Dict)["Semigroup0"], Undefined))
        return Dict{"mempty": Apply(ꞋmkEffectFn9(), func(v Any) Any {
                return func(v1 Any) Any {
                    return func(v2 Any) Any {
                        return func(v3 Any) Any {
                            return func(v4 Any) Any {
                                return func(v5 Any) Any {
                                    return func(v6 Any) Any {
                                        return func(v7 Any) Any {
                                            return func(v8 Any) Any {
                                                return mempty
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }), "Semigroup0": func(_ Any) Any {
                return semigroupEffectFn91
            },}
    }
}
func ꞋmonoidEffectFn8() Any {
    return func(dictMonoid Any) Any {
        var mempty Any = Apply(Data_Monoid.Ꞌmempty(), Apply(Effect.ꞋmonoidEffect(), dictMonoid))
        var semigroupEffectFn81 Any = Apply(ꞋsemigroupEffectFn8(), Apply(dictMonoid.(Dict)["Semigroup0"], Undefined))
        return Dict{"mempty": Apply(ꞋmkEffectFn8(), func(v Any) Any {
                return func(v1 Any) Any {
                    return func(v2 Any) Any {
                        return func(v3 Any) Any {
                            return func(v4 Any) Any {
                                return func(v5 Any) Any {
                                    return func(v6 Any) Any {
                                        return func(v7 Any) Any {
                                            return mempty
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }), "Semigroup0": func(_ Any) Any {
                return semigroupEffectFn81
            },}
    }
}
func ꞋmonoidEffectFn7() Any {
    return func(dictMonoid Any) Any {
        var mempty Any = Apply(Data_Monoid.Ꞌmempty(), Apply(Effect.ꞋmonoidEffect(), dictMonoid))
        var semigroupEffectFn71 Any = Apply(ꞋsemigroupEffectFn7(), Apply(dictMonoid.(Dict)["Semigroup0"], Undefined))
        return Dict{"mempty": Apply(ꞋmkEffectFn7(), func(v Any) Any {
                return func(v1 Any) Any {
                    return func(v2 Any) Any {
                        return func(v3 Any) Any {
                            return func(v4 Any) Any {
                                return func(v5 Any) Any {
                                    return func(v6 Any) Any {
                                        return mempty
                                    }
                                }
                            }
                        }
                    }
                }
            }), "Semigroup0": func(_ Any) Any {
                return semigroupEffectFn71
            },}
    }
}
func ꞋmonoidEffectFn6() Any {
    return func(dictMonoid Any) Any {
        var mempty Any = Apply(Data_Monoid.Ꞌmempty(), Apply(Effect.ꞋmonoidEffect(), dictMonoid))
        var semigroupEffectFn61 Any = Apply(ꞋsemigroupEffectFn6(), Apply(dictMonoid.(Dict)["Semigroup0"], Undefined))
        return Dict{"mempty": Apply(ꞋmkEffectFn6(), func(v Any) Any {
                return func(v1 Any) Any {
                    return func(v2 Any) Any {
                        return func(v3 Any) Any {
                            return func(v4 Any) Any {
                                return func(v5 Any) Any {
                                    return mempty
                                }
                            }
                        }
                    }
                }
            }), "Semigroup0": func(_ Any) Any {
                return semigroupEffectFn61
            },}
    }
}
func ꞋmonoidEffectFn5() Any {
    return func(dictMonoid Any) Any {
        var mempty Any = Apply(Data_Monoid.Ꞌmempty(), Apply(Effect.ꞋmonoidEffect(), dictMonoid))
        var semigroupEffectFn51 Any = Apply(ꞋsemigroupEffectFn5(), Apply(dictMonoid.(Dict)["Semigroup0"], Undefined))
        return Dict{"mempty": Apply(ꞋmkEffectFn5(), func(v Any) Any {
                return func(v1 Any) Any {
                    return func(v2 Any) Any {
                        return func(v3 Any) Any {
                            return func(v4 Any) Any {
                                return mempty
                            }
                        }
                    }
                }
            }), "Semigroup0": func(_ Any) Any {
                return semigroupEffectFn51
            },}
    }
}
func ꞋmonoidEffectFn4() Any {
    return func(dictMonoid Any) Any {
        var mempty Any = Apply(Data_Monoid.Ꞌmempty(), Apply(Effect.ꞋmonoidEffect(), dictMonoid))
        var semigroupEffectFn41 Any = Apply(ꞋsemigroupEffectFn4(), Apply(dictMonoid.(Dict)["Semigroup0"], Undefined))
        return Dict{"mempty": Apply(ꞋmkEffectFn4(), func(v Any) Any {
                return func(v1 Any) Any {
                    return func(v2 Any) Any {
                        return func(v3 Any) Any {
                            return mempty
                        }
                    }
                }
            }), "Semigroup0": func(_ Any) Any {
                return semigroupEffectFn41
            },}
    }
}
func ꞋmonoidEffectFn3() Any {
    return func(dictMonoid Any) Any {
        var mempty Any = Apply(Data_Monoid.Ꞌmempty(), Apply(Effect.ꞋmonoidEffect(), dictMonoid))
        var semigroupEffectFn31 Any = Apply(ꞋsemigroupEffectFn3(), Apply(dictMonoid.(Dict)["Semigroup0"], Undefined))
        return Dict{"mempty": Apply(ꞋmkEffectFn3(), func(v Any) Any {
                return func(v1 Any) Any {
                    return func(v2 Any) Any {
                        return mempty
                    }
                }
            }), "Semigroup0": func(_ Any) Any {
                return semigroupEffectFn31
            },}
    }
}
func ꞋmonoidEffectFn2() Any {
    return func(dictMonoid Any) Any {
        var mempty Any = Apply(Data_Monoid.Ꞌmempty(), Apply(Effect.ꞋmonoidEffect(), dictMonoid))
        var semigroupEffectFn21 Any = Apply(ꞋsemigroupEffectFn2(), Apply(dictMonoid.(Dict)["Semigroup0"], Undefined))
        return Dict{"mempty": Apply(ꞋmkEffectFn2(), func(v Any) Any {
                return func(v1 Any) Any {
                    return mempty
                }
            }), "Semigroup0": func(_ Any) Any {
                return semigroupEffectFn21
            },}
    }
}
func ꞋmonoidEffectFn10() Any {
    return func(dictMonoid Any) Any {
        var mempty Any = Apply(Data_Monoid.Ꞌmempty(), Apply(Effect.ꞋmonoidEffect(), dictMonoid))
        var semigroupEffectFn101 Any = Apply(ꞋsemigroupEffectFn10(), Apply(dictMonoid.(Dict)["Semigroup0"], Undefined))
        return Dict{"mempty": Apply(ꞋmkEffectFn10(), func(v Any) Any {
                return func(v1 Any) Any {
                    return func(v2 Any) Any {
                        return func(v3 Any) Any {
                            return func(v4 Any) Any {
                                return func(v5 Any) Any {
                                    return func(v6 Any) Any {
                                        return func(v7 Any) Any {
                                            return func(v8 Any) Any {
                                                return func(v9 Any) Any {
                                                    return mempty
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }), "Semigroup0": func(_ Any) Any {
                return semigroupEffectFn101
            },}
    }
}
func ꞋmonoidEffectFn1() Any {
    return func(dictMonoid Any) Any {
        var mempty Any = Apply(Data_Monoid.Ꞌmempty(), Apply(Effect.ꞋmonoidEffect(), dictMonoid))
        var semigroupEffectFn11 Any = Apply(ꞋsemigroupEffectFn1(), Apply(dictMonoid.(Dict)["Semigroup0"], Undefined))
        return Dict{"mempty": Apply(ꞋmkEffectFn1(), func(v Any) Any {
                return mempty
            }), "Semigroup0": func(_ Any) Any {
                return semigroupEffectFn11
            },}
    }
}


// Foreign values

var foreign = Foreign("Effect.Uncurried")

var ᛌmkEffectFn1_once Once
var ᛧmkEffectFn1 Any

func ꞋmkEffectFn1() Any { 
    ᛌmkEffectFn1_once.Do(func() {
        ᛧmkEffectFn1 = Get(foreign, "mkEffectFn1")
    })
    return ᛧmkEffectFn1
}

var ᛌmkEffectFn2_once Once
var ᛧmkEffectFn2 Any

func ꞋmkEffectFn2() Any { 
    ᛌmkEffectFn2_once.Do(func() {
        ᛧmkEffectFn2 = Get(foreign, "mkEffectFn2")
    })
    return ᛧmkEffectFn2
}

var ᛌmkEffectFn3_once Once
var ᛧmkEffectFn3 Any

func ꞋmkEffectFn3() Any { 
    ᛌmkEffectFn3_once.Do(func() {
        ᛧmkEffectFn3 = Get(foreign, "mkEffectFn3")
    })
    return ᛧmkEffectFn3
}

var ᛌmkEffectFn4_once Once
var ᛧmkEffectFn4 Any

func ꞋmkEffectFn4() Any { 
    ᛌmkEffectFn4_once.Do(func() {
        ᛧmkEffectFn4 = Get(foreign, "mkEffectFn4")
    })
    return ᛧmkEffectFn4
}

var ᛌmkEffectFn5_once Once
var ᛧmkEffectFn5 Any

func ꞋmkEffectFn5() Any { 
    ᛌmkEffectFn5_once.Do(func() {
        ᛧmkEffectFn5 = Get(foreign, "mkEffectFn5")
    })
    return ᛧmkEffectFn5
}

var ᛌmkEffectFn6_once Once
var ᛧmkEffectFn6 Any

func ꞋmkEffectFn6() Any { 
    ᛌmkEffectFn6_once.Do(func() {
        ᛧmkEffectFn6 = Get(foreign, "mkEffectFn6")
    })
    return ᛧmkEffectFn6
}

var ᛌmkEffectFn7_once Once
var ᛧmkEffectFn7 Any

func ꞋmkEffectFn7() Any { 
    ᛌmkEffectFn7_once.Do(func() {
        ᛧmkEffectFn7 = Get(foreign, "mkEffectFn7")
    })
    return ᛧmkEffectFn7
}

var ᛌmkEffectFn8_once Once
var ᛧmkEffectFn8 Any

func ꞋmkEffectFn8() Any { 
    ᛌmkEffectFn8_once.Do(func() {
        ᛧmkEffectFn8 = Get(foreign, "mkEffectFn8")
    })
    return ᛧmkEffectFn8
}

var ᛌmkEffectFn9_once Once
var ᛧmkEffectFn9 Any

func ꞋmkEffectFn9() Any { 
    ᛌmkEffectFn9_once.Do(func() {
        ᛧmkEffectFn9 = Get(foreign, "mkEffectFn9")
    })
    return ᛧmkEffectFn9
}

var ᛌmkEffectFn10_once Once
var ᛧmkEffectFn10 Any

func ꞋmkEffectFn10() Any { 
    ᛌmkEffectFn10_once.Do(func() {
        ᛧmkEffectFn10 = Get(foreign, "mkEffectFn10")
    })
    return ᛧmkEffectFn10
}

var ᛌrunEffectFn1_once Once
var ᛧrunEffectFn1 Any

func ꞋrunEffectFn1() Any { 
    ᛌrunEffectFn1_once.Do(func() {
        ᛧrunEffectFn1 = Get(foreign, "runEffectFn1")
    })
    return ᛧrunEffectFn1
}

var ᛌrunEffectFn2_once Once
var ᛧrunEffectFn2 Any

func ꞋrunEffectFn2() Any { 
    ᛌrunEffectFn2_once.Do(func() {
        ᛧrunEffectFn2 = Get(foreign, "runEffectFn2")
    })
    return ᛧrunEffectFn2
}

var ᛌrunEffectFn3_once Once
var ᛧrunEffectFn3 Any

func ꞋrunEffectFn3() Any { 
    ᛌrunEffectFn3_once.Do(func() {
        ᛧrunEffectFn3 = Get(foreign, "runEffectFn3")
    })
    return ᛧrunEffectFn3
}

var ᛌrunEffectFn4_once Once
var ᛧrunEffectFn4 Any

func ꞋrunEffectFn4() Any { 
    ᛌrunEffectFn4_once.Do(func() {
        ᛧrunEffectFn4 = Get(foreign, "runEffectFn4")
    })
    return ᛧrunEffectFn4
}

var ᛌrunEffectFn5_once Once
var ᛧrunEffectFn5 Any

func ꞋrunEffectFn5() Any { 
    ᛌrunEffectFn5_once.Do(func() {
        ᛧrunEffectFn5 = Get(foreign, "runEffectFn5")
    })
    return ᛧrunEffectFn5
}

var ᛌrunEffectFn6_once Once
var ᛧrunEffectFn6 Any

func ꞋrunEffectFn6() Any { 
    ᛌrunEffectFn6_once.Do(func() {
        ᛧrunEffectFn6 = Get(foreign, "runEffectFn6")
    })
    return ᛧrunEffectFn6
}

var ᛌrunEffectFn7_once Once
var ᛧrunEffectFn7 Any

func ꞋrunEffectFn7() Any { 
    ᛌrunEffectFn7_once.Do(func() {
        ᛧrunEffectFn7 = Get(foreign, "runEffectFn7")
    })
    return ᛧrunEffectFn7
}

var ᛌrunEffectFn8_once Once
var ᛧrunEffectFn8 Any

func ꞋrunEffectFn8() Any { 
    ᛌrunEffectFn8_once.Do(func() {
        ᛧrunEffectFn8 = Get(foreign, "runEffectFn8")
    })
    return ᛧrunEffectFn8
}

var ᛌrunEffectFn9_once Once
var ᛧrunEffectFn9 Any

func ꞋrunEffectFn9() Any { 
    ᛌrunEffectFn9_once.Do(func() {
        ᛧrunEffectFn9 = Get(foreign, "runEffectFn9")
    })
    return ᛧrunEffectFn9
}

var ᛌrunEffectFn10_once Once
var ᛧrunEffectFn10 Any

func ꞋrunEffectFn10() Any { 
    ᛌrunEffectFn10_once.Do(func() {
        ᛧrunEffectFn10 = Get(foreign, "runEffectFn10")
    })
    return ᛧrunEffectFn10
}


