// Code generated by psgo. DO NOT EDIT.

package Data_Array_ST_Partial

import . "github.com/purescript-native/go-runtime"

import (
	"project.localhost/purescript-native/output/Control.Monad.ST.Uncurried"
)

type _ = Any

func Ꞌpoke() Any {
    return func(_ Any) Any {
        return Apply(Control_Monad_ST_Uncurried.ꞋrunSTFn3(), ꞋpokeImpl())
    }
}
func Ꞌpeek() Any {
    return func(_ Any) Any {
        return Apply(Control_Monad_ST_Uncurried.ꞋrunSTFn2(), ꞋpeekImpl())
    }
}


// Foreign values

var foreign = Foreign("Data.Array.ST.Partial")

var ᛌpeekImpl_once Once
var ᛧpeekImpl Any

func ꞋpeekImpl() Any { 
    ᛌpeekImpl_once.Do(func() {
        ᛧpeekImpl = Get(foreign, "peekImpl")
    })
    return ᛧpeekImpl
}

var ᛌpokeImpl_once Once
var ᛧpokeImpl Any

func ꞋpokeImpl() Any { 
    ᛌpokeImpl_once.Do(func() {
        ᛧpokeImpl = Get(foreign, "pokeImpl")
    })
    return ᛧpokeImpl
}


