// Code generated by psgo. DO NOT EDIT.

package Control_Plus

import . "github.com/purescript-native/go-runtime"

import (
	"project.localhost/purescript-native/output/Control.Alt"
)

type _ = Any

func ꞋPlus_ṩDict() Any {
    return func(x Any) Any {
        return x
    }
}

var ᛌplusArray_once Once
var ᛧplusArray Any

func ꞋplusArray() Any {
    ᛌplusArray_once.Do(func() {
        ᛧplusArray = Dict{"empty": []Any{}, "Alt0": func(_ Any) Any {
            return Control_Alt.ꞋaltArray()
        },}
    })
return ᛧplusArray
}


func Ꞌempty() Any {
    return func(dict Any) Any {
        return dict.(Dict)["empty"]
    }
}



