// Code generated by psgo. DO NOT EDIT.

package Data_Profunctor_Costrong

import . "github.com/purescript-native/go-runtime"

import (
)

type _ = Any

func ꞋCostrong_ṩDict() Any {
    return func(x Any) Any {
        return x
    }
}
func Ꞌunsecond() Any {
    return func(dict Any) Any {
        return dict.(Dict)["unsecond"]
    }
}
func Ꞌunfirst() Any {
    return func(dict Any) Any {
        return dict.(Dict)["unfirst"]
    }
}



