// Code generated by psgo. DO NOT EDIT.

package Data_Array_Partial

import . "github.com/purescript-native/go-runtime"

import (
	"project.localhost/purescript-native/output/Data.Array"
	"project.localhost/purescript-native/output/Data.Ring"
)

type _ = Any

func ꞋunsafeIndex() Any {
    return Apply(Data_Array.ꞋunsafeIndex(), Undefined)
}
func Ꞌsub() Any {
    return Apply(Data_Ring.Ꞌsub(), Data_Ring.ꞋringInt())
}
func Ꞌtail() Any {
    return func(_ Any) Any {
        return func(xs Any) Any {
            return Apply(Data_Array.Ꞌslice(), 1, Apply(Data_Array.Ꞌlength(), xs), xs)
        }
    }
}
func Ꞌlast() Any {
    return func(_ Any) Any {
        return func(xs Any) Any {
            return Apply(ꞋunsafeIndex(), xs, Apply(Ꞌsub(), Apply(Data_Array.Ꞌlength(), xs), 1))
        }
    }
}
func Ꞌinit() Any {
    return func(_ Any) Any {
        return func(xs Any) Any {
            return Apply(Data_Array.Ꞌslice(), 0, Apply(Ꞌsub(), Apply(Data_Array.Ꞌlength(), xs), 1), xs)
        }
    }
}
func Ꞌhead() Any {
    return func(_ Any) Any {
        return func(xs Any) Any {
            return Apply(ꞋunsafeIndex(), xs, 0)
        }
    }
}



