// Code generated by psgo. DO NOT EDIT.

package Data_Profunctor_Closed

import . "github.com/purescript-native/go-runtime"

import (
	"project.localhost/purescript-native/output/Control.Semigroupoid"
	"project.localhost/purescript-native/output/Data.Profunctor"
)

type _ = Any

func ꞋClosed_ṩDict() Any {
    return func(x Any) Any {
        return x
    }
}

var ᛌclosedFunction_once Once
var ᛧclosedFunction Any

func ꞋclosedFunction() Any {
    ᛌclosedFunction_once.Do(func() {
        ᛧclosedFunction = Dict{"closed": Apply(Control_Semigroupoid.Ꞌcompose(), Control_Semigroupoid.ꞋsemigroupoidFn()), "Profunctor0": func(_ Any) Any {
            return Data_Profunctor.ꞋprofunctorFn()
        },}
    })
return ᛧclosedFunction
}


func Ꞌclosed() Any {
    return func(dict Any) Any {
        return dict.(Dict)["closed"]
    }
}



