// Code generated by psgo. DO NOT EDIT.

package Control_Monad_ST_Uncurried

import . "github.com/purescript-native/go-runtime"

import (
)

type _ = Any




// Foreign values

var foreign = Foreign("Control.Monad.ST.Uncurried")

var ᛌmkSTFn1_once Once
var ᛧmkSTFn1 Any

func ꞋmkSTFn1() Any { 
    ᛌmkSTFn1_once.Do(func() {
        ᛧmkSTFn1 = Get(foreign, "mkSTFn1")
    })
    return ᛧmkSTFn1
}

var ᛌmkSTFn2_once Once
var ᛧmkSTFn2 Any

func ꞋmkSTFn2() Any { 
    ᛌmkSTFn2_once.Do(func() {
        ᛧmkSTFn2 = Get(foreign, "mkSTFn2")
    })
    return ᛧmkSTFn2
}

var ᛌmkSTFn3_once Once
var ᛧmkSTFn3 Any

func ꞋmkSTFn3() Any { 
    ᛌmkSTFn3_once.Do(func() {
        ᛧmkSTFn3 = Get(foreign, "mkSTFn3")
    })
    return ᛧmkSTFn3
}

var ᛌmkSTFn4_once Once
var ᛧmkSTFn4 Any

func ꞋmkSTFn4() Any { 
    ᛌmkSTFn4_once.Do(func() {
        ᛧmkSTFn4 = Get(foreign, "mkSTFn4")
    })
    return ᛧmkSTFn4
}

var ᛌmkSTFn5_once Once
var ᛧmkSTFn5 Any

func ꞋmkSTFn5() Any { 
    ᛌmkSTFn5_once.Do(func() {
        ᛧmkSTFn5 = Get(foreign, "mkSTFn5")
    })
    return ᛧmkSTFn5
}

var ᛌmkSTFn6_once Once
var ᛧmkSTFn6 Any

func ꞋmkSTFn6() Any { 
    ᛌmkSTFn6_once.Do(func() {
        ᛧmkSTFn6 = Get(foreign, "mkSTFn6")
    })
    return ᛧmkSTFn6
}

var ᛌmkSTFn7_once Once
var ᛧmkSTFn7 Any

func ꞋmkSTFn7() Any { 
    ᛌmkSTFn7_once.Do(func() {
        ᛧmkSTFn7 = Get(foreign, "mkSTFn7")
    })
    return ᛧmkSTFn7
}

var ᛌmkSTFn8_once Once
var ᛧmkSTFn8 Any

func ꞋmkSTFn8() Any { 
    ᛌmkSTFn8_once.Do(func() {
        ᛧmkSTFn8 = Get(foreign, "mkSTFn8")
    })
    return ᛧmkSTFn8
}

var ᛌmkSTFn9_once Once
var ᛧmkSTFn9 Any

func ꞋmkSTFn9() Any { 
    ᛌmkSTFn9_once.Do(func() {
        ᛧmkSTFn9 = Get(foreign, "mkSTFn9")
    })
    return ᛧmkSTFn9
}

var ᛌmkSTFn10_once Once
var ᛧmkSTFn10 Any

func ꞋmkSTFn10() Any { 
    ᛌmkSTFn10_once.Do(func() {
        ᛧmkSTFn10 = Get(foreign, "mkSTFn10")
    })
    return ᛧmkSTFn10
}

var ᛌrunSTFn1_once Once
var ᛧrunSTFn1 Any

func ꞋrunSTFn1() Any { 
    ᛌrunSTFn1_once.Do(func() {
        ᛧrunSTFn1 = Get(foreign, "runSTFn1")
    })
    return ᛧrunSTFn1
}

var ᛌrunSTFn2_once Once
var ᛧrunSTFn2 Any

func ꞋrunSTFn2() Any { 
    ᛌrunSTFn2_once.Do(func() {
        ᛧrunSTFn2 = Get(foreign, "runSTFn2")
    })
    return ᛧrunSTFn2
}

var ᛌrunSTFn3_once Once
var ᛧrunSTFn3 Any

func ꞋrunSTFn3() Any { 
    ᛌrunSTFn3_once.Do(func() {
        ᛧrunSTFn3 = Get(foreign, "runSTFn3")
    })
    return ᛧrunSTFn3
}

var ᛌrunSTFn4_once Once
var ᛧrunSTFn4 Any

func ꞋrunSTFn4() Any { 
    ᛌrunSTFn4_once.Do(func() {
        ᛧrunSTFn4 = Get(foreign, "runSTFn4")
    })
    return ᛧrunSTFn4
}

var ᛌrunSTFn5_once Once
var ᛧrunSTFn5 Any

func ꞋrunSTFn5() Any { 
    ᛌrunSTFn5_once.Do(func() {
        ᛧrunSTFn5 = Get(foreign, "runSTFn5")
    })
    return ᛧrunSTFn5
}

var ᛌrunSTFn6_once Once
var ᛧrunSTFn6 Any

func ꞋrunSTFn6() Any { 
    ᛌrunSTFn6_once.Do(func() {
        ᛧrunSTFn6 = Get(foreign, "runSTFn6")
    })
    return ᛧrunSTFn6
}

var ᛌrunSTFn7_once Once
var ᛧrunSTFn7 Any

func ꞋrunSTFn7() Any { 
    ᛌrunSTFn7_once.Do(func() {
        ᛧrunSTFn7 = Get(foreign, "runSTFn7")
    })
    return ᛧrunSTFn7
}

var ᛌrunSTFn8_once Once
var ᛧrunSTFn8 Any

func ꞋrunSTFn8() Any { 
    ᛌrunSTFn8_once.Do(func() {
        ᛧrunSTFn8 = Get(foreign, "runSTFn8")
    })
    return ᛧrunSTFn8
}

var ᛌrunSTFn9_once Once
var ᛧrunSTFn9 Any

func ꞋrunSTFn9() Any { 
    ᛌrunSTFn9_once.Do(func() {
        ᛧrunSTFn9 = Get(foreign, "runSTFn9")
    })
    return ᛧrunSTFn9
}

var ᛌrunSTFn10_once Once
var ᛧrunSTFn10 Any

func ꞋrunSTFn10() Any { 
    ᛌrunSTFn10_once.Do(func() {
        ᛧrunSTFn10 = Get(foreign, "runSTFn10")
    })
    return ᛧrunSTFn10
}


