// Code generated by psgo. DO NOT EDIT.

package Unsafe_Coerce

import . "github.com/purescript-native/go-runtime"

import (
)

type _ = Any




// Foreign values

var foreign = Foreign("Unsafe.Coerce")

var ᛌunsafeCoerce_once Once
var ᛧunsafeCoerce Any

func ꞋunsafeCoerce() Any { 
    ᛌunsafeCoerce_once.Do(func() {
        ᛧunsafeCoerce = Get(foreign, "unsafeCoerce")
    })
    return ᛧunsafeCoerce
}


