// Code generated by psgo. DO NOT EDIT.

package Data_Unit

import . "github.com/purescript-native/go-runtime"

import (
)

type _ = Any




// Foreign values

var foreign = Foreign("Data.Unit")

var ᛌunit_once Once
var ᛧunit Any

func Ꞌunit() Any { 
    ᛌunit_once.Do(func() {
        ᛧunit = Get(foreign, "unit")
    })
    return ᛧunit
}


