// Code generated by psgo. DO NOT EDIT.

package Data_Ord_Min

import . "github.com/purescript-native/go-runtime"

import (
	"project.localhost/purescript-native/output/Data.Semigroup"
	"project.localhost/purescript-native/output/Data.Show"
	"project.localhost/purescript-native/output/Data.Ord"
	"project.localhost/purescript-native/output/Data.Bounded"
)

type _ = Any

func Ꞌappend() Any {
    return Apply(Data_Semigroup.Ꞌappend(), Data_Semigroup.ꞋsemigroupString())
}
func ꞋMin() Any {
    return func(x Any) Any {
        return x
    }
}
func ꞋshowMin() Any {
    return func(dictShow Any) Any {
        var show Any = Apply(Data_Show.Ꞌshow(), dictShow)
        return Dict{"show": func(v Any) Any {
                return Apply(Ꞌappend(), "(Min ", Apply(Ꞌappend(), Apply(show, v), ")"))
            },}
    }
}
func ꞋsemigroupMin() Any {
    return func(dictOrd Any) Any {
        var min Any = Apply(Data_Ord.Ꞌmin(), dictOrd)
        return Dict{"append": func(v Any) Any {
                return func(v1 Any) Any {
                    return Apply(min, v, v1)
                }
            },}
    }
}

var ᛌnewtypeMin_once Once
var ᛧnewtypeMin Any

func ꞋnewtypeMin() Any {
    ᛌnewtypeMin_once.Do(func() {
        ᛧnewtypeMin = Dict{"Coercible0": func(_ Any) Any {
            return Undefined
        },}
    })
return ᛧnewtypeMin
}


func ꞋmonoidMin() Any {
    return func(dictBounded Any) Any {
        var semigroupMin1 Any = Apply(ꞋsemigroupMin(), Apply(dictBounded.(Dict)["Ord0"], Undefined))
        return Dict{"mempty": Apply(Data_Bounded.Ꞌtop(), dictBounded), "Semigroup0": func(_ Any) Any {
                return semigroupMin1
            },}
    }
}
func ꞋeqMin() Any {
    return func(dictEq Any) Any {
        return dictEq
    }
}
func ꞋordMin() Any {
    return func(dictOrd Any) Any {
        var compare Any = Apply(Data_Ord.Ꞌcompare(), dictOrd)
        var eqMin1 Any = Apply(ꞋeqMin(), Apply(dictOrd.(Dict)["Eq0"], Undefined))
        return Dict{"compare": func(v Any) Any {
                return func(v1 Any) Any {
                    return Apply(compare, v, v1)
                }
            }, "Eq0": func(_ Any) Any {
                return eqMin1
            },}
    }
}



