// Code generated by psgo. DO NOT EDIT.

package Data_Profunctor_Cochoice

import . "github.com/purescript-native/go-runtime"

import (
)

type _ = Any

func ꞋCochoice_ṩDict() Any {
    return func(x Any) Any {
        return x
    }
}
func Ꞌunright() Any {
    return func(dict Any) Any {
        return dict.(Dict)["unright"]
    }
}
func Ꞌunleft() Any {
    return func(dict Any) Any {
        return dict.(Dict)["unleft"]
    }
}



