// Code generated by psgo. DO NOT EDIT.

package Effect_Ref

import . "github.com/purescript-native/go-runtime"

import (
	"project.localhost/purescript-native/output/Data.Functor"
	"project.localhost/purescript-native/output/Effect"
)

type _ = Any

func Ꞌvoid() Any {
    return Apply(Data_Functor.Ꞌvoid(), Effect.ꞋfunctorEffect())
}
func Ꞌnew() Any {
    return Ꞌ_new()
}
func Ꞌmodifyꞌ() Any {
    return ꞋmodifyImpl()
}
func Ꞌmodify() Any {
    return func(f Any) Any {
        return Apply(Ꞌmodifyꞌ(), func(s Any) Any {
            var sꞌ Any = Apply(f, s)
            return Dict{"state": sꞌ, "value": sꞌ,}
        })
    }
}
func Ꞌmodify_() Any {
    return func(f Any) Any {
        return func(s Any) Any {
            return Apply(Ꞌvoid(), Apply(Ꞌmodify(), f, s))
        }
    }
}


// Foreign values

var foreign = Foreign("Effect.Ref")

var ᛌ_new_once Once
var ᛧ_new Any

func Ꞌ_new() Any { 
    ᛌ_new_once.Do(func() {
        ᛧ_new = Get(foreign, "_new")
    })
    return ᛧ_new
}

var ᛌnewWithSelf_once Once
var ᛧnewWithSelf Any

func ꞋnewWithSelf() Any { 
    ᛌnewWithSelf_once.Do(func() {
        ᛧnewWithSelf = Get(foreign, "newWithSelf")
    })
    return ᛧnewWithSelf
}

var ᛌread_once Once
var ᛧread Any

func Ꞌread() Any { 
    ᛌread_once.Do(func() {
        ᛧread = Get(foreign, "read")
    })
    return ᛧread
}

var ᛌmodifyImpl_once Once
var ᛧmodifyImpl Any

func ꞋmodifyImpl() Any { 
    ᛌmodifyImpl_once.Do(func() {
        ᛧmodifyImpl = Get(foreign, "modifyImpl")
    })
    return ᛧmodifyImpl
}

var ᛌwrite_once Once
var ᛧwrite Any

func Ꞌwrite() Any { 
    ᛌwrite_once.Do(func() {
        ᛧwrite = Get(foreign, "write")
    })
    return ᛧwrite
}


