// Code generated by psgo. DO NOT EDIT.

package Control_Monad_ST_Global

import . "github.com/purescript-native/go-runtime"

import (
	"project.localhost/purescript-native/output/Unsafe.Coerce"
)

type _ = Any

func ꞋtoEffect() Any {
    return Unsafe_Coerce.ꞋunsafeCoerce()
}



