// Code generated by psgo. DO NOT EDIT.

package Safe_Coerce

import . "github.com/purescript-native/go-runtime"

import (
	"project.localhost/purescript-native/output/Unsafe.Coerce"
)

type _ = Any

func Ꞌcoerce() Any {
    return func(_ Any) Any {
        return Unsafe_Coerce.ꞋunsafeCoerce()
    }
}



